services:
  nginx:
    container_name: react-nginx
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    networks:
      - nginx_network

  build:
    container_name: react-build
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    ports:
      - "${PORT:-5173}:5173"
    environment:
      - NODE_ENV={$NODE_ENV:-development}
    networks:
      - nginx_network
    volumes:
      - .:/app:delegated
      - node_modules:/app/node_modules

volumes:
  node_modules:

networks:
  nginx_network:
    external: true