version: '3.8'
services:
  react-app:
    container_name: react-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-3000}:80"
    environment:
      - NODE_ENV=${NODE_ENV:-development}