services:
  nginx:
    container_name: react-nginx
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx-${DOCKER_BUILD_TARGET:-development}
    networks:
      - nginx_network

  build:
    container_name: react-build
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    ports:
      - "${PORT:-5173}:5173"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    networks:
      - nginx_network
    volumes:
      - .:/app:delegated
      - node_modules:/app/node_modules
    profiles:
      - build

  react-app-dev:
    image: node:22-alpine
    container_name: react-app-dev
    working_dir: /app
    environment:
      - NODE_ENV=development
    networks:
      - nginx_network
    volumes:
      - .:/app:delegated
      - node_modules:/app/node_modules
    command: >
      sh -c "npm install && npm run dev"
    ports:
      - "${DEV_PORT:-5173}:5173"
    profiles:
      - dev

volumes:
  node_modules:

networks:
  nginx_network:
    external: true